<?php

namespace App\Support;

/**
 * Validates a merchant's chosen admin-panel accent colour.
 *
 * The panel's primary palette is now generated by Filament itself
 * (`Color::hex()` registered as the panel's `primary`), so Filament runs
 * its own WCAG contrast maths to pick legible text shades for buttons,
 * toggles, and selected states. This class only decides whether a given
 * hex is a *usable* accent in the first place — near-black, near-white,
 * and greyscale colours can't drive a legible coloured palette, so callers
 * (Store::adminAccentColor) treat them as "unset" and fall back to the
 * panel default.
 *
 * (Historical note: this class used to generate the palette + emit CSS
 * variable overrides. That approach was wrong for Filament v5 — it locked
 * shade *assignments* to the default palette and only repainted the
 * variables, which broke button-text contrast. The generation is gone;
 * only the usability guard remains.)
 */
class AccentPalette
{
    /** Emerald-500 RGB — the fallback used when a hex can't be parsed. */
    private const FALLBACK = [16, 185, 129];

    /**
     * A syntactically valid 3- or 6-digit hex colour (with or without `#`).
     */
    public static function isValid(?string $hex): bool
    {
        if (! is_string($hex)) {
            return false;
        }

        $h = ltrim(trim($hex), '#');

        return (strlen($h) === 3 || strlen($h) === 6) && ctype_xdigit($h);
    }

    /**
     * Whether a colour is a *usable* admin accent. Near-black, near-white,
     * and very desaturated (grey) inputs can't drive a legible coloured
     * palette, so they're rejected and the panel keeps its default.
     *
     * Thresholds operate on HSL: reject L outside [0.18, 0.82] (too dark /
     * too light to tell shades apart) or S below 0.20 (greyscale).
     */
    public static function isUsable(?string $hex): bool
    {
        if (! self::isValid($hex)) {
            return false;
        }

        [, $s, $l] = self::rgbToHsl(...self::parse((string) $hex));

        return $s >= 0.20 && $l >= 0.18 && $l <= 0.82;
    }

    /**
     * @return array{0:int,1:int,2:int}
     */
    public static function parse(string $hex): array
    {
        $hex = ltrim(trim($hex), '#');

        if (strlen($hex) === 3) {
            $hex = $hex[0] . $hex[0] . $hex[1] . $hex[1] . $hex[2] . $hex[2];
        }

        if (strlen($hex) !== 6 || ! ctype_xdigit($hex)) {
            return self::FALLBACK;
        }

        return [
            (int) hexdec(substr($hex, 0, 2)),
            (int) hexdec(substr($hex, 2, 2)),
            (int) hexdec(substr($hex, 4, 2)),
        ];
    }

    /**
     * RGB (0–255) → HSL. Hue in degrees (0–360), S + L in 0–1.
     *
     * @return array{0:float,1:float,2:float} [h, s, l]
     */
    private static function rgbToHsl(int $r, int $g, int $b): array
    {
        $r /= 255;
        $g /= 255;
        $b /= 255;

        $max = max($r, $g, $b);
        $min = min($r, $g, $b);
        $l = ($max + $min) / 2;
        $d = $max - $min;

        if ($d == 0.0) {
            return [0.0, 0.0, $l]; // achromatic (grey/black/white)
        }

        $s = $l > 0.5 ? $d / (2 - $max - $min) : $d / ($max + $min);

        if ($max === $r) {
            $h = (($g - $b) / $d) + ($g < $b ? 6 : 0);
        } elseif ($max === $g) {
            $h = (($b - $r) / $d) + 2;
        } else {
            $h = (($r - $g) / $d) + 4;
        }

        return [$h * 60, $s, $l];
    }
}
